name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build
      run: sudo apt install libconfig++-dev python-dev libboost-all-dev python-numpy pytest
    - name: make
      run: make
    - name: pysetup
      run: python setup.py install
    - name: pytest
      run: pytest
